title: Wishlist Rocket
author: Wishlist Rocket
email: support@wishlistwhale.com
description: >
  With Wishlist Rocket, add a 'Add to wishlist' button to your store & customers can add items to their wishlists
image:
  path: '/assets/img/Banner.png'
  alt: Wishlist Rocket allows customers to add items to their wishlists
baseurl: ''
url: 'https://wishlistwhale.com'
header_pages:
  - index.md
  - help.md
footer_links:
  about:
    link: /about.html
    title: About Us
  privacy:
    link: /policy.html
    title: Privacy Policy
  terms:
    link: /terms.html
    title: Terms & Conditions
defaults:
    - scope:
        path: "assets/img"
      values:
        image: true
theme: minima
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
